<?php

/*
 * We require autoload generated by the Composer, register the "FacadeLoader"
 * and try to run statically method on our test "Main" class,
 * that we imported with "Facades" namespace prefix.
 */

use App\FacadeLoader;
use Facades\App\Main;

require_once 'vendor/autoload.php';

FacadeLoader::setFacadeNamespace('Facades\\');
FacadeLoader::getInstance()->register();

Main::run();
